server:
  port: 9094
  servlet:
    context-path: /userApi
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: gebi-user-9094
  cloud:
    nacos:
      server-addr: 172.17.0.2:8848 #注册中心
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.138.38:3306/ge_bi
    username: gebi
    password: 789159357Zj
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 3
    host: 124.71.138.38
    port: 6379
    timeout: 5000
    password: 789159357Zj
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  rabbitmq:
    addresses: 172.17.0.3
    port: 5672
    username: guest
    password: 789159357Zj
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000
          multiplier: 1.5
          max-interval: 60000
  config:
    activate:
      on-profile:
        - prod
dubbo:
  application:
    name: dubbo-user
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://172.17.0.2:8848
  scan:
    base-packages: com.madou.user.dubbo
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.madou.user.api
  default-flat-param-object: false

mybatis-plus:
  mapperPackage: com.madou.**.mapper
  type-aliases-package: com.madou.user
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

#鱼聪明
yuapi:
  client:
    access-key: ux7bpq5mqr8db3n0dfhd46bunkebr8f3
    secret-key: eg6zsakkz0av0f6jae3g3cw163nw56hc
#支付宝支付
alipay:
  appId: 9021000122698871
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCBHgcsrfkv0Nr53utTVrahPROCYrubDm5pplOuP++h3PnDdUNWw+h6l3kB8X6Kl8/tt2OESWC97z8/TnBm7dG/LDVMQ+qLsjBATsRXYzhe/HwYdHxy+x2n3Hn1mVcTdP30U4WspRPBtD/cTQk8Ad/q3DWXbWiX6GWcRB9J+OrB2bu55thxRkFfUsfsYLempc4ClrTgt142nkyTJWf9ZWIFezNkLFRsMH/Gas+vN4Y9dx7mnQIvqS0tdJta6Uc9KBxDggN3qtOhkbh2HxVDzCUVp0cuuTV6jeji7V5f9QEV5NSex3J6yMc2OA9XatkuKeH9lSCXaPSOK7uVpT0/pzIJAgMBAAECggEAQPcp5vo2Si/NLjJSt6EGzUQc39rryE3PkksFCcTTvt6fsQ/8bNivzZcPZMHsyLEwBsziPrpo+cg6S5EdDz0T7xvASXpWtilXC9RWCB49S9XAXtGlmHjvZ/mQR9n6rSiNavTnaoG42hrmkuMUBWRwFQztzh5XpS9iiOjh0Wd0P0qmi8R74LKjposd/fV/PvX+Y3aVznI2MxDXg4ZYEEk2kp6Str7sed6SY1l47u7Ok4ACVqVrdjozveQ6CRdpiYZ+InoEQ3sOcJsypJ9H/vTiKHMhT14I/K9D3be/R/zFjaeteH7y5VMLLnkFFdnXhMw1SyT6669FIvfooeBlaJQB/QKBgQC8toZtGfZ+zl2Z5260NhZaO8bBklCfpmsW4cowxLF3bdtjSSu9umgKLGT/VHfMrlh5g6Kp4T6t5DGBISGHS53PqNmAlR9QzXXpg4p1z5gWKE7G7+JCxzXFZUKz7Hj3AhhA7DH+4oZ5rzyHQN25tMH8LLP+x6JiF0W5xLrxlNYG2wKBgQCvJ6+j72y7BMxPC2Ke7DMGjIo9gFnt/vALJ2qTNK/bcHbZruAsq6hFJIwSqrLzM0n7oDPRJbMEElX90xLzEvoqYBLzRcxcHWQFqnNr6RVId6BMnVduNioS4o5IWqgVxAsYV7mMb4pGH+vMak/P4tXxqwHUzPyzSVeW7jLhtjfl6wKBgQCjRFcw9RFpzCj3Cl+g0lqsXqMqvee6+EQWW+qOHt5bMVRppdiOIUP56UbIENBE6WHqX5TP3OxZjd+2lG9pmmZCTxc+Q8YAJoIpMYENRDmUkfL18nySwb8ntN/swl41dj59jNwEZP9rL8zyR5CNJnHeNt7TQuyeaPwOKMKEV/yDmQKBgHGaIdcH0NOzlvelgL9mnumeeYLOHoW4FeSGGh+DypNe7Bbfz1Hpu+esfpUU1Z/bIh7rlvANrX/0jIVmQyIYqtyVF3VlTdhoz5jFJrtUn5My02sdmblHtB4vhuzyr5X+YtvU+elV5q74wS0BvuYsT2rA6R0mHrgB16dystmmH7clAoGAFDfjBgb2NvjS41fFbBPj32UHwXN4W9R9Nb2E+ERwhr36ztzfIHA871Za497/+jUXOMmsu44Iz3la6wZMKWCweSUJfqeZ7Vfz5gchjHPO17159S0WRd2vpS32QEtzPr8FYYDBpGGQVuwD/VM9E4w16qq10SeMMwZxRsr7rAMuXdc=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtArMSQwGm+etlaXghRdcgodQc8AaVRbN9oReCP1VID8145qeP238rRFr55kUdnUnUGUlb4bDAsUIZfNHexGM4hceEtv3AETBkm7r/5o5VFi86zWF536rg2GDqDbNIu0apTXIqpSYAqZRlwTCuz0BXrWWe/dd4O0KF/WLLh5Doyrghcu0oVzd6UahZ5IJdOzpmAXuSW+8fNxaddyBtFoIfa+NFc/xbqcCwhjaP4bT8NCfBeYmhYraqdVgM2ljINs8jS+DZkmLnbDvBlIQwt/8irKoSN2aCYc/GzCSPxh7L/dWiGppekQU55K5T6pU9cQDRSKzWMgqxlpF2ak3MjcLxQIDAQAB

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # 打开RPC调用鉴权
  check-same-token: true
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  activity-timeout: 1800000
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
