server:
  port: 8099
spring:
  application:
    name: gebi-gateway-8099
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  cloud:
    nacos:
      server-addr: 192.168.10.151:8848 #注册中心
    gateway:
      routes:
        - id: gebi-user-9094 #用户服务
          uri: lb://gebi-user-9094
          predicates:
            - Path=/userApi/**
        - id: gebi-chart-9095 #图表分析服务
          uri: lb://gebi-chart-9095
          predicates:
            - Path=/chartApi/**
        - id: gebi-text-9096 #文本转换服务
          uri: lb://gebi-text-9096
          predicates:
            - Path=/textApi/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:9094"
              - "http://localhost:9095"
              - "http://localhost:9096"
              - "http://localhost:8000"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
  config:
    activate:
      on-profile:
        - dev
knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: 用户服务
        url: /userApi/v3/api-docs?group=default
        order: 1
        context-path: /userApi #添加请求前缀
      - name: 文本服务
        url: /textApi/v3/api-docs?group=default
        order: 1
        context-path: /textApi
      - name: 图表服务
        url: /chartApi/v3/api-docs?group=default
        order: 1
        context-path: /chartApi
security:
  # white list
  ignore:
    whites:
      - /**
      - /code
      - /userApi/user/logout
      - /userApi/user/login
      - /index/**
      - /userApi/user/register
      - /*/v3/api-docs
      - /csrf
      - /ChartApi
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # 打开RPC调用鉴权
  check-same-token: true
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  activity-timeout: 1800000
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
